apiVersion: v1
kind: ConfigMap
metadata:
  name: consoledot-health-metrics-config
data:
  prometheus-host: prometheus.crcs02ue1.devshift.net
  SLO_config.json: |
    {
      "SLO_Queries" :[
        { "service": "3scale",
          "queries": [
          {
            "metric": "ERROR_RATE",
            "query": "sum(rate(api_3scale_gateway_api_status{status=%225xx%22}[8h]))/sum(rate(api_3scale_gateway_api_status[8h]))",
            "target_slo": 0.001
          }
        ]},
        { "service": "entitlements",
          "queries": [
          {
            "metric": "ERROR_RATE",
            "query": "sum(rate(api_3scale_gateway_api_status{status="5xx",%20exported_service="entitlements"}[4h]))%20/%20sum(rate(api_3scale_gateway_api_status{exported_service="entitlements"}[4h]))",
            "target_slo": 0.01
          }
        ]},
        { "service": "rbac",
          "queries": [
          {
            "metric": "ERROR_RATE",
            "query": "1 - avg_over_time(service:sli:status_5xx:pctl5rate5m{environment="prod",exported_service="rbac"}[4h])",
            "target_slo": 0.99
          }
        ]}
      ]
    }
